#include "raylib/raylib.h"
#include "Types.h"

const char *utilsPlayerStateToText( PlayerState state ) {

    switch ( state ) {
        case PLAYER_STATE_IDLE: return "PLAYER_STATE_IDLE";
        case PLAYER_STATE_WALKING_FORWARD: return "PLAYER_STATE_WALKING_FORWARD";
        case PLAYER_STATE_WALKING_BACKWARD: return "PLAYER_STATE_WALKING_BACKWARD";
        case PLAYER_STATE_CROUCHING: return "PLAYER_STATE_CROUCHING";
        case PLAYER_STATE_JUMPING_STRAIGHT: return "PLAYER_STATE_JUMPING_STRAIGHT";
        case PLAYER_STATE_JUMPING_FORWARD: return "PLAYER_STATE_JUMPING_FORWARD";
        case PLAYER_STATE_JUMPING_BACKWARD: return "PLAYER_STATE_JUMPING_BACKWARD";
        case PLAYER_STATE_LP: return "PLAYER_STATE_LP";
        case PLAYER_STATE_MP: return "PLAYER_STATE_MP";
        case PLAYER_STATE_HP: return "PLAYER_STATE_HP";
        case PLAYER_STATE_LK: return "PLAYER_STATE_LK";
        case PLAYER_STATE_MK: return "PLAYER_STATE_MK";
        case PLAYER_STATE_HK: return "PLAYER_STATE_HK";
        case PLAYER_STATE_LP_CLOSE: return "PLAYER_STATE_LP_CLOSE";
        case PLAYER_STATE_MP_CLOSE: return "PLAYER_STATE_MP_CLOSE";
        case PLAYER_STATE_HP_CLOSE: return "PLAYER_STATE_HP_CLOSE";
        case PLAYER_STATE_LK_CLOSE: return "PLAYER_STATE_LK_CLOSE";
        case PLAYER_STATE_MK_CLOSE: return "PLAYER_STATE_MK_CLOSE";
        case PLAYER_STATE_HK_CLOSE: return "PLAYER_STATE_HK_CLOSE";
        case PLAYER_STATE_LP_CROUCH: return "PLAYER_STATE_LP_CROUCH";
        case PLAYER_STATE_MP_CROUCH: return "PLAYER_STATE_MP_CROUCH";
        case PLAYER_STATE_HP_CROUCH: return "PLAYER_STATE_HP_CROUCH";
        case PLAYER_STATE_LK_CROUCH: return "PLAYER_STATE_LK_CROUCH";
        case PLAYER_STATE_MK_CROUCH: return "PLAYER_STATE_MK_CROUCH";
        case PLAYER_STATE_HK_CROUCH: return "PLAYER_STATE_HK_CROUCH";
        case PLAYER_STATE_JUMP_COOLDOWN: return "PLAYER_STATE_JUMP_COOLDOWN";
        case PLAYER_STATE_LP_JUMP_STRAIGHT: return "PLAYER_STATE_LP_STRAIGHT";
        case PLAYER_STATE_MP_JUMP_STRAIGHT: return "PLAYER_STATE_MP_STRAIGHT";
        case PLAYER_STATE_HP_JUMP_STRAIGHT: return "PLAYER_STATE_HP_STRAIGHT";
        case PLAYER_STATE_LK_JUMP_STRAIGHT: return "PLAYER_STATE_LK_STRAIGHT";
        case PLAYER_STATE_MK_JUMP_STRAIGHT: return "PLAYER_STATE_MK_STRAIGHT";
        case PLAYER_STATE_HK_JUMP_STRAIGHT: return "PLAYER_STATE_HK_STRAIGHT";
        case PLAYER_STATE_LP_JUMP_FORWARD: return "PLAYER_STATE_LP_FORWARD";
        case PLAYER_STATE_MP_JUMP_FORWARD: return "PLAYER_STATE_MP_FORWARD";
        case PLAYER_STATE_HP_JUMP_FORWARD: return "PLAYER_STATE_HP_FORWARD";
        case PLAYER_STATE_LK_JUMP_FORWARD: return "PLAYER_STATE_LK_FORWARD";
        case PLAYER_STATE_MK_JUMP_FORWARD: return "PLAYER_STATE_MK_FORWARD";
        case PLAYER_STATE_HK_JUMP_FORWARD: return "PLAYER_STATE_HK_FORWARD";
        case PLAYER_STATE_LP_JUMP_BACKWARD: return "PLAYER_STATE_LP_BACKWARD";
        case PLAYER_STATE_MP_JUMP_BACKWARD: return "PLAYER_STATE_MP_BACKWARD";
        case PLAYER_STATE_HP_JUMP_BACKWARD: return "PLAYER_STATE_HP_BACKWARD";
        case PLAYER_STATE_LK_JUMP_BACKWARD: return "PLAYER_STATE_LK_BACKWARD";
        case PLAYER_STATE_MK_JUMP_BACKWARD: return "PLAYER_STATE_MK_BACKWARD";
        case PLAYER_STATE_HK_JUMP_BACKWARD: return "PLAYER_STATE_HK_BACKWARD";
        case PLAYER_STATE_LAST: return "PLAYER_STATE_LAST";
        default: return "";
    }

}

const char *utilsEditorModeToText( EditorMode mode ) {

    switch ( mode ) {
        case EDITOR_MODE_COLLISION_BOX: return "EDITOR_MODE_COLLISION_BOX";
        case EDITOR_MODE_HIT_BOX_0: return "EDITOR_MODE_HIT_BOX_0";
        case EDITOR_MODE_HIT_BOX_1: return "EDITOR_MODE_HIT_BOX_1";
        case EDITOR_MODE_HIT_BOX_2: return "EDITOR_MODE_HIT_BOX_2";
        case EDITOR_MODE_HURT_BOX_0: return "EDITOR_MODE_HURT_BOX_0";
        case EDITOR_MODE_HURT_BOX_1: return "EDITOR_MODE_HURT_BOX_1";
        case EDITOR_MODE_HURT_BOX_2: return "EDITOR_MODE_HURT_BOX_2";
        default: return "";
    }

}